apiVersion : apps/v1
kind : Deployment
metadata : 
  name : sample-hello-world-deployment
  lables :
    app : hello-world
spec :
  replicas : 2
  selector : 
    matchLables :
      app : hello-world
  template :
    metadata:
      lables:
        app : hello-world
    spec:
      containers:
      - name : hello-world-pod
        image : bhavani005/sample-hello-world
        ports :
        - containerPort : 80 

---

appVersion : v1
kind : Service
metadata:
  name : sample-hello-world-service
spec:
  selector :
    app : hello-world
  ports :
    - protocol : TCP 
      port : 9798
      targetPort : 80
    
