apiVersion : apps/v1
kind : Deployment
metadata : 
  name : sample-hello-world-deployment
  labels :
    app : hello-world
spec :
  replicas : 1
  selector : 
    matchLabels :
      app : hello-world
  template :
    metadata:
      labels:
        app : hello-world
    spec:
      containers:
      - name : hello-world-pod
        image : bhavani005/sample-hello-world
        ports :
        - containerPort : 80 
        env :
        - name : DOCKERHUB_USERNAME
          valueFrom :
            secretKeyRef :
              name : demo-secret 
              key : username
        - name : DOCKERHUB_PASSWORD
          valueFrom :
            secretKeyRef :
              name : demo-secret 
              key : password
---
apiVersion : v1
kind : Service
metadata:
  name : sample-hello-world-service
spec:
  selector :
    app : hello-world
  ports :
    - protocol : TCP 
      port : 8081
      targetPort : 80
      nodePort : 30008
  type : LoadBalancer
    
